name: Build Docker Image

on:
  push:
    branches:
      - dev-itn1  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Updated to v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v2  # Updated to v3
      with:
        dotnet-version: '8.0.x'

    - name: Build and publish .NET app
      run: |
        cd jobs
        dotnet restore jobs.csproj
        dotnet publish jobs.csproj -c Release -o out

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Updated to v2

    - name: Build Docker image
      run: |
        docker build -t localhandsv1:latest -f ./jobs/Dockerfile ./jobs
