name: main

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Updated to v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v2  # Updated to v3
      with:
        dotnet-version: '8.0.x'

    - name: Build and publish .NET app
      run: |
        dotnet restore
        dotnet publish -c Release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Updated to v2

    - name: Log in to ACR
      uses: azure/docker-login@v1  # Updated to v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/localhandsv1:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/localhandsv1:${{ github.sha }}

    - name: Azure CLI login
      uses: azure/login@v1  # Updated to v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp config container set --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/localhandsv1:${{ github.sha }}
        az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
